// Fetching countries types
const FETCH_COUNTRIES_LOADING = 'FETCH_COUNTRIES_LOADING'
const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR'

// Fetching regions types
const FETCH_REGIONS_LOADING = 'FETCH_REGIONS_LOADING'
const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS'
const FETCH_REGIONS_ERROR = 'FETCH_REGIONS_ERROR'

// Fetching country detail types
const FETCH_COUNTRY_DETAIL_LOADING = 'FETCH_COUNTRY_DETAIL_LOADING'
const FETCH_COUNTRY_DETAIL_SUCCESS = 'FETCH_COUNTRY_DETAIL_SUCCESS'
const FETCH_COUNTRY_DETAIL_ERROR = 'FETCH_COUNTRY_DETAIL_ERROR'

// Dark mode
const SET_DARK_MODE = 'SET_DARK_MODE'

export {
  FETCH_COUNTRIES_LOADING,
  FETCH_COUNTRIES_SUCCESS,
  FETCH_COUNTRIES_ERROR,
  FETCH_REGIONS_LOADING,
  FETCH_REGIONS_SUCCESS,
  FETCH_REGIONS_ERROR,
  FETCH_COUNTRY_DETAIL_LOADING,
  FETCH_COUNTRY_DETAIL_SUCCESS,
  FETCH_COUNTRY_DETAIL_ERROR,
  SET_DARK_MODE
}
